'use client';

import { Download, FileText, Printer } from 'lucide-react';
import type { AIReport, SecurityReportData } from '../../lib/types';
import { Card } from '../ui/Card';
import { RiskScoreBadge } from '../ui/RiskBadge';
import { StatsCard } from '../ui/StatsCard';
import { Button } from '../ui/Button';
import { Markdown } from '../shared/Markdown';

function downloadFile(filename: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// No backend export endpoint exists (reports are computed per-request,
// never persisted — see ARCHITECTURE.md) — "export" here means exporting
// what's already rendered client-side: a JSON download of the raw report
// payload, a Markdown download of the AI narrative, or the browser's own
// print-to-PDF, rather than a server-generated PDF/file.
function ExportButtons({ report }: { report: SecurityReportData }) {
  const narrativeMarkdown = report.aiReport?.aiStatus === 'SUCCESS' ? buildNarrativeMarkdown(report.aiReport) : null;

  return (
    <div className="flex flex-wrap gap-2">
      <Button variant="outline" size="sm" onClick={() => downloadFile('security-report.json', JSON.stringify(report, null, 2), 'application/json')}>
        <Download className="size-4" /> Export JSON
      </Button>
      {narrativeMarkdown ? (
        <Button variant="outline" size="sm" onClick={() => downloadFile('security-report.md', narrativeMarkdown, 'text/markdown')}>
          <FileText className="size-4" /> Export Markdown
        </Button>
      ) : null}
      <Button variant="outline" size="sm" onClick={() => window.print()}>
        <Printer className="size-4" /> Print / Save as PDF
      </Button>
    </div>
  );
}

function buildNarrativeMarkdown(aiReport: AIReport): string {
  const parts: string[] = [];
  if (aiReport.executiveSummary) parts.push(`## Executive Summary\n\n${aiReport.executiveSummary}`);
  if (aiReport.riskNarrative) parts.push(`## Risk Narrative\n\n${aiReport.riskNarrative}`);
  if (aiReport.recommendationSummary) parts.push(`## Recommendation Summary\n\n${aiReport.recommendationSummary}`);
  if (aiReport.keyObservations?.length) {
    parts.push(`## Key Observations\n\n${aiReport.keyObservations.map((o) => `- ${o}`).join('\n')}`);
  }
  if (aiReport.limitations?.length) {
    parts.push(`## Limitations\n\n${aiReport.limitations.map((o) => `- ${o}`).join('\n')}`);
  }
  return parts.join('\n\n');
}

function AINarrative({ aiReport }: { aiReport: AIReport }) {
  if (aiReport.aiStatus === 'FAILED') {
    return (
      <Card title="AI Narrative">
        <p className="text-sm text-destructive">
          The AI narrative could not be generated: {aiReport.error ?? 'unknown error'}. The structured report above
          is unaffected.
        </p>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      {aiReport.executiveSummary ? (
        <Card title="Executive Summary">
          <Markdown content={aiReport.executiveSummary} />
        </Card>
      ) : null}
      {aiReport.riskNarrative ? (
        <Card title="Risk Analysis">
          <Markdown content={aiReport.riskNarrative} />
        </Card>
      ) : null}
      {aiReport.recommendationSummary ? (
        <Card title="Recommendations">
          <Markdown content={aiReport.recommendationSummary} />
        </Card>
      ) : null}
      {aiReport.keyObservations && aiReport.keyObservations.length > 0 ? (
        <Card title="Key Observations">
          <ul className="list-inside list-disc space-y-1 text-sm">
            {aiReport.keyObservations.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </Card>
      ) : null}
      {aiReport.limitations && aiReport.limitations.length > 0 ? (
        <Card title="Limitations">
          <ul className="list-inside list-disc space-y-1 text-sm text-muted-foreground">
            {aiReport.limitations.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </Card>
      ) : null}
      {aiReport.metadata ? (
        <p className="text-xs text-muted-foreground">
          Generated by {aiReport.metadata.provider}/{aiReport.metadata.model} in {aiReport.metadata.latencyMs}ms ·{' '}
          {aiReport.metadata.totalTokens} tokens · ${aiReport.metadata.estimatedCostUsd.toFixed(4)}
        </p>
      ) : null}
    </div>
  );
}

export function ReportViewer({ report }: { report: SecurityReportData }) {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-2">
        <div className="grid flex-1 grid-cols-1 gap-4 sm:grid-cols-3">
          <StatsCard
            label="Overall Risk"
            value={
              report.executive.overallRiskScore !== null ? (
                <RiskScoreBadge score={report.executive.overallRiskScore} />
              ) : (
                '—'
              )
            }
          />
          <StatsCard
            label="Compliance Score"
            value={report.executive.complianceScore !== null ? `${report.executive.complianceScore}%` : '—'}
          />
          <StatsCard label="Open Findings" value={report.executive.openFindingsCount ?? '—'} />
        </div>
      </div>

      <ExportButtons report={report} />

      {report.aiReport ? (
        <AINarrative aiReport={report.aiReport} />
      ) : (
        <Card title="AI Narrative">
          <p className="text-sm text-muted-foreground">
            No AI narrative was requested for this report. Generate one with Summary or Full Report mode above.
          </p>
        </Card>
      )}
    </div>
  );
}
