import type { ToolDefinition } from '../../types/tool.types.js';
import type { AIContext } from '../../types/context.types.js';
import type { ToolRegistry } from '../../tools/tool-registry.js';
import { recommendationService } from '../../../services/analysis/recommendation.service.js';
import { findingService } from '../../../services/analysis/finding.service.js';
import { getOwnedAsset } from '../../../services/assets/ownership.js';
import { resourceRepository } from '../../../repositories/resource.repository.js';
import type { Requester } from '../../../services/assets/ownership.js';
import {
  assetIdInputSchema,
  recommendationEngineToolOutputSchema,
  findingLookupToolOutputSchema,
  assetLookupToolOutputSchema,
} from './recommendation.schemas.js';
import type { z } from 'zod';

type AssetIdInput = z.infer<typeof assetIdInputSchema>;

const PAGE_SIZE = 500;

function toRequester(context: AIContext): Requester {
  return { id: context.user.id, role: context.user.role as Requester['role'] };
}

// Every tool here wraps EXISTING backend services — no Recommendation is
// ever generated by this agent. RecommendationEngineTool reads already-
// persisted Recommendation rows (services/analysis/recommendation.service.ts,
// unchanged: "Every Finding generates one Recommendation," created by
// FindingService as a side effect of rule evaluation, never here).
// FindingLookupTool reads the Finding rows those recommendations are
// keyed to, so the agent can cross-reference (Phase 20 goal #6) without
// re-querying per recommendation.

export const recommendationEngineTool: ToolDefinition = {
  name: 'recommendation_engine_list',
  description:
    'Lists the existing, persisted Recommendation rows for an asset via the existing RecommendationService — one row per open Finding, generated by FindingService as a side effect of rule evaluation. Never generates a new recommendation itself.',
  inputSchema: assetIdInputSchema,
  outputSchema: recommendationEngineToolOutputSchema,
  async execute(input: AssetIdInput, context: AIContext) {
    const requester = toRequester(context);
    const result = await recommendationService.list(requester, {
      assetId: input.assetId,
      page: 1,
      limit: PAGE_SIZE,
    });
    return {
      recommendations: result.items.map((r) => ({
        id: r.id,
        findingId: r.findingId,
        title: r.title,
        description: r.description,
        estimatedImpact: r.estimatedImpact ?? '',
        priority: r.priority,
        status: r.status,
        createdAt: r.createdAt.toISOString(),
      })),
      total: result.total,
    };
  },
};

export const findingLookupTool: ToolDefinition = {
  name: 'recommendation_finding_lookup',
  description:
    "Lists this asset's existing OPEN findings via the existing FindingService — the source Findings recommendations are keyed to. Never creates or recalculates a finding.",
  inputSchema: assetIdInputSchema,
  outputSchema: findingLookupToolOutputSchema,
  async execute(input: AssetIdInput, context: AIContext) {
    const requester = toRequester(context);
    const result = await findingService.list(requester, {
      assetId: input.assetId,
      status: 'OPEN',
      page: 1,
      limit: PAGE_SIZE,
    });
    return {
      findings: result.items.map((f) => ({
        id: f.id,
        resourceId: f.resourceId,
        ruleCode: f.ruleCode,
        severity: f.severity,
        title: f.title,
        confidence: f.confidence,
      })),
      total: result.total,
    };
  },
};

export const assetLookupTool: ToolDefinition = {
  name: 'recommendation_asset_lookup',
  description:
    'Confirms ownership of the asset and returns a count of its currently discovered resources, grouped by resourceType — read from the existing Resource store.',
  inputSchema: assetIdInputSchema,
  outputSchema: assetLookupToolOutputSchema,
  async execute(input: AssetIdInput, context: AIContext) {
    const requester = toRequester(context);
    await getOwnedAsset(input.assetId, requester);
    const resources = await resourceRepository.findActiveByAsset(input.assetId);
    const resourcesByType: Record<string, number> = {};
    for (const resource of resources) {
      resourcesByType[resource.resourceType] = (resourcesByType[resource.resourceType] ?? 0) + 1;
    }
    return { assetId: input.assetId, resourceCount: resources.length, resourcesByType };
  },
};

export function registerRecommendationTools(toolRegistry: ToolRegistry): void {
  for (const tool of [recommendationEngineTool, findingLookupTool, assetLookupTool]) {
    if (!toolRegistry.has(tool.name)) {
      toolRegistry.register(tool);
    }
  }
}
