// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Runs the compiled output, not tsx-on-the-fly — see src/scripts/seed.ts's
    // own comment for why (the production image ships dist/ only).
    seed: "node dist/scripts/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
