import { prisma } from '../db/prisma.js';
import { Prisma } from '../generated/prisma/client.js';
import type { AgentPlanExecution, AgentPlanStatus } from '../generated/prisma/client.js';

export interface CreateAgentPlanExecutionInput {
  id: string;
  requestType: string;
  assetId: string;
  status: AgentPlanStatus;
}

export interface UpdateAgentPlanExecutionInput {
  status?: AgentPlanStatus;
  summary?: Prisma.InputJsonValue;
  error?: string;
  completedAt?: Date;
  durationMs?: number;
}

class AgentPlanExecutionRepository {
  // Id is supplied by the caller (the plan's own id, generated by
  // PlannerService) rather than left to @default(cuid()) — this way the
  // PLAN_CREATED event, the AggregatedPlanResult, and this audit row all
  // share one id with no translation step.
  async create(data: CreateAgentPlanExecutionInput): Promise<AgentPlanExecution> {
    return prisma.agentPlanExecution.create({
      data: {
        id: data.id,
        requestType: data.requestType,
        assetId: data.assetId,
        status: data.status,
      },
    });
  }

  async update(id: string, data: UpdateAgentPlanExecutionInput): Promise<AgentPlanExecution> {
    return prisma.agentPlanExecution.update({
      where: { id },
      data: {
        status: data.status,
        summary: data.summary,
        error: data.error,
        completedAt: data.completedAt,
        durationMs: data.durationMs,
      },
    });
  }

  async findById(id: string): Promise<AgentPlanExecution | null> {
    return prisma.agentPlanExecution.findUnique({ where: { id } });
  }

  async delete(id: string): Promise<void> {
    await prisma.agentPlanExecution.delete({ where: { id } });
  }
}

export const agentPlanExecutionRepository = new AgentPlanExecutionRepository();
